trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  AZURE_WEBAPP_NAME: 'HomeManagementApi'
  AZURE_WEBAPP_PACKAGE_PATH: '$(Build.ArtifactStagingDirectory)/publish'
  CONFIGURATION: 'Release'
  DOTNET_CORE_VERSION: '9.0.x'
  WORKING_DIRECTORY: '.'

steps:
- task: UseDotNet@2
  displayName: 'Set Package SDK '
  inputs:
    packageType: 'sdk'
    version: '$(DOTNET_CORE_VERSION)'
  continueOnError: false

- task: DotNetCoreCLI@2
  displayName: "Package Restore"
  continueOnError: false
  inputs:
    command: 'restore'
    projects: '$(WORKING_DIRECTORY)'


- task: DotNetCoreCLI@2
  displayName: "Project build"
  continueOnError: false
  inputs:
    command: 'build'
    projects: '$(WORKING_DIRECTORY)'
    arguments: '--configuration $(CONFIGURATION) --no-restore'

- task: DotNetCoreCLI@2
  displayName: "Unit Test"
  continueOnError: false
  inputs:
    command: 'test'
    projects: '$(WORKING_DIRECTORY)'
    arguments: '--no-build'

- task: DotNetCoreCLI@2
  displayName: "Publish project"
  continueOnError: false
  inputs:
    command: 'publish'
    projects: '$(WORKING_DIRECTORY)'
    arguments: '--configuration $(CONFIGURATION) --no-build --output $(AZURE_WEBAPP_PACKAGE_PATH)'

- task: PublishBuildArtifacts@1
  displayName: "Create Artifacts"
  continueOnError: false
  inputs:
    PathtoPublish: '$(AZURE_WEBAPP_PACKAGE_PATH)'
    ArtifactName: 'webapp'
    publishLocation: 'Container'

- task: DownloadBuildArtifacts@0
  displayName: "Download Artifacts"
  continueOnError: false
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'webapp'
    downloadPath: '$(Build.SourcesDirectory)'

- task: AzureRmWebAppDeployment@5
  displayName: "Deploy to Azure WebApp"
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(e6511a57-ccce-456e-8609-fadbe249291e)'
    appType: 'webApp'
    WebAppName: 'HomeManagementApi'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
