@HomeManagement_HostAddress = http://localhost:5098

###

POST {{HomeManagement_HostAddress}}/api/user/3/addUser
Content-Type: application/json

{   
    "name": "Sonu Dubey",
    "email": "sdubey@yopmail.com",
    "password": "123456",
    "city":"Kota",
    "mobileNo":"9029451159"
}

###
GET {{HomeManagement_HostAddress}}/api/user/getAllUsers

###

GET {{HomeManagement_HostAddress}}/api/user/getUserById/1